### ISSUE TITLE
Delete feature (User Story #29)

### ISSUE THREAD

**Issue by taerakwon** [Team-Taera/COMP231-F2016-GROUP1#42]
#29

**Comment by kkh0811** [comment]
Done for SQL-Side

**Comment by taerakwon** [comment]
Unit test completed

**Comment by kkh0811** [comment]
@taerakwon 
Actual hours: 1.5 hours
Challenge: The main issues was that how to get recordID selected from datagridview because
my query needed to get recordId to delete user record.

**Comment by RyanYizhaoHuang** [comment]
Implement two deleteHelper class to handle the delete userRecord function. Next step is unit testing.

**Comment by RyanYizhaoHuang** [comment]
@mekhaleganesh  you can go to my account's repo->1.29. the code for delete function in ready to go.

**Comment by RyanYizhaoHuang** [comment]
@taerakwon @kkh0811 @mekhaleganesh @domlau @prtk15 

The delete function code is ready to test.

So far, create two deleteHelper class(**DeleteUserRecordHelper and DeleteUserRecordCategoryHelper**) for deleting Record from UserRecord and UserRecordCategory table.
SQL:
DELETE FROM UserRecordCategories WHERE RecordID = @RecordID
DELETE FROM UserRecord WHERE RecordID = @RecordID

Also, create DeleteRecordController class as the intermediary class between Form and Helper class. By using the controller class, you can reduce the duplicate delete function code in the "Delete Button" and "Right-click Delete" event. Because the code in those two event for calling the delete function in same.

Remove, delete function code in the Databasehelper class.

I will submit the pull request later.

**Comment by RyanYizhaoHuang** [comment]
Task completed.
