### ISSUE TITLE
Design and code delete button to work with database

### ISSUE THREAD

**Issue by taerakwon** [Team-Taera/COMP231-F2016-GROUP1#43]

**Comment by RyanYizhaoHuang** [comment]
Finished, add delete function to right click menu and "Delete" button.

**Comment by taerakwon** [comment]
Redesigning and coding based on SOLID work.
Reassigned to @prtk15

**Comment by taerakwon** [comment]
@RyanYizhaoHuang, please update the number of hours that you contributes to this task.
Also, please update google sheet with this task # for proper date.

**Comment by RyanYizhaoHuang** [comment]
Use 2 hour to SOLID delete function, add IDelete interface, DeleteUserRecordHelper class, DeleteUserCategoryhelper. However, due to just start to SOLID, the old code of delete function haven't been removed and the SOLID delete haven't been applied yet. Will do and test later in case SOLID has problem.

**Comment by taerakwon** [comment]
Removed
