### ISSUE TITLE
Allow users to store changes that are made to existing records (User Story #28)

### ISSUE THREAD

**Issue by taerakwon** [Team-Taera/COMP231-F2016-GROUP1#47]
#28

**Comment by domlau** [comment]
Coded the edit features of existing records. Just need to make small changes to the pull request that was rejected due to the conflicts.

**Comment by domlau** [comment]
@taerakwon 
Reopened task to add in hours and explain task.
Took 7 hours in total to complete. There were db issues regarding to making the update query and there were also some issue to making the selected record view in editable form. I also had to make small changes to the pull request that was rejected due to conflicts.

**Comment by domlau** [comment]
This task is still in progress because I need to apply SOLID principles. I am going to require additional time to complete this task.

**Comment by mekhaleganesh** [comment]
finished and merged to branch 1.28.
 tested and its working
